### ISSUE TITLE
Consider using `casefold` instead of `lower`

### ISSUE THREAD

**Issue by rudolfbyker** [pywbem/nocasedict#122]
I am comparing various implementations of case-insensitive dictionaries in Python, and have found that this one uses `str.lower()` rather than `str.casefold()`. See e.g. [pydicti](https://github.com/coldfix/pydicti), which uses `casefold()` is available, and falls back to `lower()` if not available. If both fail, the key is used verbatim.

The advantage of `casefold` is that is has better unicode support than `lower`.

**Comment by andy-maier** [comment]
I agree.

**Comment by andy-maier** [comment]
I have created PR #128 for this. Please review the approach taken.

**Comment by rudolfbyker** [comment]
Looks good to me. I don't have any specific comments.

**Comment by andy-maier** [comment]
Version 1.1.0 was released to Pypi today.
