### ISSUE TITLE
Stronger typing

### ISSUE THREAD

**Issue by rudolfbyker** [pywbem/nocasedict#123]
It would be nice to have stronger typing when using the package. Currently, Mypy does not find any types when importing `from nocasedict`:

![image](https://user-images.githubusercontent.com/10025342/207594233-fb350778-30e4-4cbb-90d0-31c9826256e2.png)

A good first step would be to [add the py.typed marker](https://dev.to/whtsky/don-t-forget-py-typed-for-your-typed-python-package-2aa3), and ensure that all function arguments and return values have type hints. The project could benefit from Mypy linting itself, but that is not required.

**Comment by andy-maier** [comment]
We are supporting Python 2.7 and >=3.4 with this project. How can we add type hints without giving up support for Python 2.7, 3.4, 3.5?

**Comment by rudolfbyker** [comment]
It's possible to specify the types in separate `.pyi` files, but it's obviously much harder to maintain than having the types in the code. See https://peps.python.org/pep-0484/#stub-files :)

**Comment by andy-maier** [comment]
Thanks for that link.
I think we will introduce a version 2.0.0 of nocasedict that requires Python>=3.6 and defines type hints in the code. That allows adding functionality to version 1.0.0 should that ever be needed.

**Comment by rudolfbyker** [comment]
Good idea! I'll keep an eye out for that.

**Comment by andy-maier** [comment]
@rudolfbyker Hi Rudolf. PR #136 uses type hints has been merged to master. Could you please double check whether that meets your expectations? Please reopen this issue or a new one if it does not. Thanks!

**Comment by rudolfbyker** [comment]
Looks good to me.
